services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
     - ./:/code

  db:
    image: postgres:16.3-bullseye
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - /var/lib/postgresql:/var/lib/postgresql